removed --cache

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -109,38 +109,46 @@ pipeline {
 		}*/
 
 		stage('Build Angular UI') {
-			steps {
-			  timeout(time: 40, unit: 'MINUTES') {   // ⛔ Angular hang protection
-				dir('ims-angular-ui') {
-					sh '''
-					set -e
-					 echo "🔍 Enforcing Node 20"
-                        export PATH="$NODEJS_HOME/bin:$PATH"
-                        export NG_BUILD_CACHE=/var/jenkins_home/angular-cache
-                        mkdir -p $NG_BUILD_CACHE
-                        export NG_PERSISTENT_BUILD_CACHE=1
+          steps {
+            timeout(time: 40, unit: 'MINUTES') {
+              dir('ims-angular-ui') {
+                sh '''
+                  set -e
 
-                        node -v
-                        npm -v
+                  echo "🔍 Enforcing Node 20"
+                  export PATH="$NODEJS_HOME/bin:$PATH"
 
-                        if ! node -v | grep -q "v20"; then
-                          echo "❌ Node 20 not active. Aborting."
-                          exit 1
-                        fi
-            echo "Installing Angular dependencies and building for production"
-              npm ci --no-audit --no-fund
-              npm run build -- --configuration=production --cache
+                  export NG_BUILD_CACHE=/var/jenkins_home/angular-cache
+                  export NG_PERSISTENT_BUILD_CACHE=1
+                  mkdir -p $NG_BUILD_CACHE
+
+                  node -v
+                  npm -v
+
+                  if ! node -v | grep -q "v20"; then
+                    echo "❌ Node 20 not active. Aborting."
+                    exit 1
+                  fi
+
+                  echo "📦 Installing dependencies"
+                  npm ci --no-audit --no-fund
+
+                  echo "🏗️ Building Angular for production"
+                  npm run build -- --configuration=production
+                '''
+              }
+            }
+
+            sh '''
+              set -e
+              echo "📦 Preparing Angular dist for Docker deployment"
+              rm -rf ${ANGULAR_DIST}
+              mkdir -p ${ANGULAR_DIST}
+              cp -r ims-angular-ui/dist/angular-ui-cli/* ${ANGULAR_DIST}/
             '''
+          }
         }
-        }
-        sh '''
-        echo "Preparing Angular dist for Docker deployment"
-          rm -rf ${ANGULAR_DIST}
-          mkdir -p ${ANGULAR_DIST}
-          cp -r ims-angular-ui/dist/** ${ANGULAR_DIST}/
-        '''
-    }
-}
+
 
 
 
